spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://umc-db.c15co4yvzlav.ap-northeast-2.rds.amazonaws.com/baemin?serverTimezone=Asia/Seoul
    password: 20190976sswu