spring:
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: admin
  url: jdbc:mysql://umc-db.c15co4yvzlav.ap-northeast-2.rds.amazonaws.com/baemin
  password: 20190976sswu
mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

mail:
  host: smtp.naver.com
  port: 465
  username: wngml203@naver.com
  password: 689QDKFDBU3Q
  properties:
    mail.smtp.auth: true
    mail.smtp.ssl.enable: true

cloud:
  aws:
    credentials:
      accessKey: AKIA3DFQLJYEXSGZXZJU
      secretKey: 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
    s3:
      bucket: baeminbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

          logging.level.org.springframework.boot.autoconfigure: ERROR